"""Initial revision

Revision ID: 43559ba75394
Revises: 
Create Date: 2025-04-15 18:51:54.187903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43559ba75394'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('niu', sa.String(), nullable=True))
    op.add_column('users', sa.Column('nif', sa.String(), nullable=True))
    op.drop_column('users', 'inn')
    op.drop_column('users', 'snils')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('snils', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('inn', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'nif')
    op.drop_column('users', 'niu')
    # ### end Alembic commands ###
